#端口号配置
server:
  port: 8089

#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.133:3306/db_gyhr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty

# jwt配置
jwt:
  secret: com.gyhr
  # 60分钟过期
  expiration: 3600000

#配置登录请求url
gyhr:
  loginUrl: /api/user/login

# 图片上传
img:
  uploadPath: D:/Work/images
  loadPath: file:D:\\Work\\images\\

alipay:
  appId: 
  appPrivateKey: 
  alipayPublicKey: 
  notifyUrl: 

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'